# Generated by Django 4.2.3 on 2023-07-15 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='in_stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='pick_up_locations',
            field=models.TextField(blank=True, help_text='input comma separated items', null=True),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='variations',
            field=models.TextField(blank=True),
        ),
    ]
