# Generated by Django 4.2.3 on 2023-07-16 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_saleproduct_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
